/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMondelTestRouteImport } from './routes/api/mondel-test'
import { Route as WorkspaceDashboardIndexRouteImport } from './routes/_workspace/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMondelTestRoute = ApiMondelTestRouteImport.update({
  id: '/api/mondel-test',
  path: '/api/mondel-test',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceDashboardIndexRoute = WorkspaceDashboardIndexRouteImport.update({
  id: '/_workspace/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/mondel-test': typeof ApiMondelTestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof WorkspaceDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/mondel-test': typeof ApiMondelTestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof WorkspaceDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/mondel-test': typeof ApiMondelTestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_workspace/dashboard/': typeof WorkspaceDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/mondel-test' | '/api/auth/$' | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/mondel-test' | '/api/auth/$' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/api/mondel-test'
    | '/api/auth/$'
    | '/_workspace/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMondelTestRoute: typeof ApiMondelTestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  WorkspaceDashboardIndexRoute: typeof WorkspaceDashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mondel-test': {
      id: '/api/mondel-test'
      path: '/api/mondel-test'
      fullPath: '/api/mondel-test'
      preLoaderRoute: typeof ApiMondelTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/dashboard/': {
      id: '/_workspace/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof WorkspaceDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMondelTestRoute: ApiMondelTestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  WorkspaceDashboardIndexRoute: WorkspaceDashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
